Repository flow-pie/StudentMarketPlace, pull requests merged in 2025-05, with the labels that each got.

#34 Feature/project setup
  .idea/misc.xml
  API-Core/.env.example
  API-Core/app/__init__.py
  API-Core/app/extensions.py
  API-Core/requirements.txt
Labels: project Setup

#39 Mysql db schema
  db schema
Labels: DB & ORM

#40 flask sqlalchemy
  app.py
  config.py
  models.py
Labels: DB & ORM

#41 ✅[AUTH] RESOLVED ISSUE: #6 and #7
  .idea/StudentMarketPlace.iml
  API-Core/.env.example
  API-Core/__init__.py
  API-Core/app/__init__.py
  API-Core/app/blueprints/auth/routes.py
  API-Core/app/decorators/auth.py
  API-Core/app/extensions.py
  API-Core/app/models/conversation.py
  API-Core/app/models/favourite.py
  API-Core/app/models/transaction.py
  API-Core/app/schemas/auth.py
  API-Core/postman/MarketplaceAPI.postman_collection.json
  API-Core/run.py
  API-Core/tests/__init__.py
  API-Core/tests/conftest.py
  API-Core/tests/test_auth.py
  API-Core/tests/test_protected_routes.py
Labels: Authentication

#42 Feature/item listings 01
  .idea/dataSources.xml
  API-Core/app/__init__.py
  API-Core/app/blueprints/auth/routes.py
  API-Core/app/blueprints/items/__init__.py
  API-Core/app/blueprints/items/routes.py
  API-Core/app/blueprints/routes.py
  API-Core/app/extensions.py
  API-Core/app/models/__init__.py
  API-Core/app/models/item.py
  API-Core/app/models/user.py
  API-Core/app/schemas/item.py
  API-Core/app/services/item.py
  API-Core/app/services/user.py
  API-Core/assets/style.css
  API-Core/report.html
  API-Core/run.py
Labels: Item Listings (Part 1)

#45 [FEAT] ISSUE: #12
  API-Core/app/blueprints/items/routes.py
  API-Core/app/schemas/item.py
  API-Core/app/services/item.py
Labels: Item Listings (Part 2)

#47 ✨ FEAT: Add Image Management, Pagination & Advanced Filtering for Items
  API-Core/app/__init__.py
  API-Core/app/blueprints/item_images/images.py
  API-Core/app/blueprints/items/routes.py
  API-Core/app/config.py
  API-Core/app/models/item.py
  API-Core/app/models/item_image.py
  API-Core/app/schemas/item.py
  API-Core/app/services/item.py
  API-Core/app/services/item_images.py
Labels: Extra Item Features

#74 feature/auth-2
  API-Core/app/__init__.py
  API-Core/app/blueprints/auth/routes.py
  API-Core/app/models/user.py
  API-Core/app/services/auth.py
Labels: Authentication

#75 FEAT issue #20
  API-Core/app/blueprints/messages/routes.py
  API-Core/app/schemas/message.py
  API-Core/app/services/message.py
  API-Core/tests/test_messages.py
Labels: Messaging
